// <auto-generated />
using System;
using GestionTrabajosDeGradoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionTrabajosDeGradoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.asesor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("disponibilidad")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int?>("id_usuario")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__asesor__3213E83FDE027B5D");

                    b.HasIndex("id_usuario");

                    b.ToTable("asesor", (string)null);
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.asesor_trabajo", b =>
                {
                    b.Property<int>("id_asesor")
                        .HasColumnType("int");

                    b.Property<int>("id_trabajo")
                        .HasColumnType("int");

                    b.Property<string>("rol_asesor")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("id_asesor", "id_trabajo")
                        .HasName("PK__asesor_t__1731CA9B75417F54");

                    b.HasIndex("id_trabajo");

                    b.ToTable("asesor_trabajos");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.director", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("id_escuela")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__director__3213E83F77F44967");

                    b.HasIndex("id_escuela");

                    b.HasIndex("id_usuario");

                    b.ToTable("director", (string)null);
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.escuela", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("creditos")
                        .HasColumnType("int");

                    b.Property<string>("estado")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int?>("id_facultad")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PK__escuela__3213E83F8CEE3000");

                    b.HasIndex("id_facultad");

                    b.ToTable("escuela", (string)null);
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.especializacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PK__especial__3213E83FD2A8E451");

                    b.ToTable("especializacion", (string)null);
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.estudiante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("creditos_aprobados")
                        .HasColumnType("int");

                    b.Property<int?>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("matricula")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.HasKey("id")
                        .HasName("PK__estudian__3213E83F2FB2D120");

                    b.HasIndex("id_usuario");

                    b.HasIndex(new[] { "matricula" }, "UQ__estudian__30962D15A64E0E26")
                        .IsUnique()
                        .HasFilter("[matricula] IS NOT NULL");

                    b.ToTable("estudiante", (string)null);
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.evento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("id_trabajo")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id")
                        .HasName("PK__eventos__3213E83F529BFDFD");

                    b.HasIndex("id_trabajo");

                    b.HasIndex("id_usuario");

                    b.ToTable("eventos");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.facultad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("estado")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("nombre")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("id")
                        .HasName("PK__facultad__3213E83F7717D40D");

                    b.ToTable("facultad", (string)null);
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.historial_de_cambio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("id_autor")
                        .HasColumnType("int");

                    b.Property<int?>("id_propuesta")
                        .HasColumnType("int");

                    b.Property<int?>("id_trabajo")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id")
                        .HasName("PK__historia__3213E83F5536B92F");

                    b.HasIndex("id_autor");

                    b.HasIndex("id_propuesta");

                    b.HasIndex("id_trabajo");

                    b.ToTable("historial_de_cambios");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.jurado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("disponibilidad")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__jurado__3213E83F4EEE99A0");

                    b.HasIndex("id_usuario");

                    b.ToTable("jurado", (string)null);
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.linea_investigacion", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("estado")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int?>("id_escuela")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PK__linea_in__3213E83F496E2D75");

                    b.HasIndex("id_escuela");

                    b.ToTable("linea_investigacion", (string)null);
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.propuesta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_director")
                        .HasColumnType("int");

                    b.Property<int>("id_investigacion")
                        .HasColumnType("int");

                    b.Property<string>("tipo_trabajo")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id")
                        .HasName("PK__propuest__3213E83F36348942");

                    b.HasIndex("id_director");

                    b.HasIndex("id_investigacion");

                    b.ToTable("propuestas");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.trabajos_de_grado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("anteproyecto")
                        .HasMaxLength(2500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2500)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("fecha_fin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime");

                    b.Property<int?>("id_propuesta")
                        .HasColumnType("int");

                    b.Property<string>("justificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("objetivo_general")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("objetivos_especificos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("planteamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("progreso")
                        .HasColumnType("tinyint");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("trabajo")
                        .HasMaxLength(2500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2500)");

                    b.HasKey("id")
                        .HasName("PK__trabajos__3213E83F26E602C0");

                    b.HasIndex("id_propuesta");

                    b.ToTable("trabajos_de_grado", (string)null);
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("contraseña")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("correo")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("direccion")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("estado")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<DateTime?>("fecha_ingreso")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("fecha_ultimo_ingreso")
                        .HasColumnType("datetime");

                    b.Property<string>("genero")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<int?>("id_escuela")
                        .HasColumnType("int");

                    b.Property<string>("imagen")
                        .HasMaxLength(2500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2500)");

                    b.Property<string>("nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("id")
                        .HasName("PK__usuario__3213E83F485A2C8A");

                    b.HasIndex("id_escuela");

                    b.HasIndex(new[] { "correo" }, "UQ__usuario__2A586E0B539BDA0B")
                        .IsUnique()
                        .HasFilter("[correo] IS NOT NULL");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("asesor_especializacion", b =>
                {
                    b.Property<int>("id_asesor")
                        .HasColumnType("int");

                    b.Property<int>("id_especializacion")
                        .HasColumnType("int");

                    b.HasKey("id_asesor", "id_especializacion")
                        .HasName("PK__asesor_e__032BBB8827B05D50");

                    b.HasIndex("id_especializacion");

                    b.ToTable("asesor_especializacion", (string)null);
                });

            modelBuilder.Entity("estudiante_propuestum", b =>
                {
                    b.Property<int>("id_estudiante")
                        .HasColumnType("int");

                    b.Property<int>("id_propuesta")
                        .HasColumnType("int");

                    b.HasKey("id_estudiante", "id_propuesta")
                        .HasName("PK__estudian__AB3AE03F73FD0E51");

                    b.HasIndex("id_propuesta");

                    b.ToTable("estudiante_propuesta", (string)null);
                });

            modelBuilder.Entity("estudiante_trabajo", b =>
                {
                    b.Property<int>("id_estudiante")
                        .HasColumnType("int");

                    b.Property<int>("id_trabajo")
                        .HasColumnType("int");

                    b.HasKey("id_estudiante", "id_trabajo")
                        .HasName("PK__estudian__249A903F6930AAE6");

                    b.HasIndex("id_trabajo");

                    b.ToTable("estudiante_trabajo", (string)null);
                });

            modelBuilder.Entity("jurados_trabajo", b =>
                {
                    b.Property<int>("id_jurado")
                        .HasColumnType("int");

                    b.Property<int>("id_trabajo")
                        .HasColumnType("int");

                    b.HasKey("id_jurado", "id_trabajo")
                        .HasName("PK__jurados___35CDF266FAB5383C");

                    b.HasIndex("id_trabajo");

                    b.ToTable("jurados_trabajos", (string)null);
                });

            modelBuilder.Entity("usuario_escuela", b =>
                {
                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<int>("id_escuela")
                        .HasColumnType("int");

                    b.HasKey("id_usuario", "id_escuela")
                        .HasName("PK__usuario___81ECA796F7584B4B");

                    b.HasIndex("id_escuela");

                    b.ToTable("usuario_escuelas", (string)null);
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.asesor", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.usuario", "id_usuarioNavigation")
                        .WithMany("asesors")
                        .HasForeignKey("id_usuario")
                        .HasConstraintName("FK__asesor__id_usuar__35BCFE0A");

                    b.Navigation("id_usuarioNavigation");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.asesor_trabajo", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.asesor", "id_asesorNavigation")
                        .WithMany("asesor_trabajos")
                        .HasForeignKey("id_asesor")
                        .IsRequired()
                        .HasConstraintName("FK__asesor_tr__id_as__6FE99F9F");

                    b.HasOne("GestionTrabajosDeGradoAPI.Models.trabajos_de_grado", "id_trabajoNavigation")
                        .WithMany("asesor_trabajos")
                        .HasForeignKey("id_trabajo")
                        .IsRequired()
                        .HasConstraintName("FK__asesor_tr__id_tr__70DDC3D8");

                    b.Navigation("id_asesorNavigation");

                    b.Navigation("id_trabajoNavigation");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.director", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.escuela", "id_escuelaNavigation")
                        .WithMany("directors")
                        .HasForeignKey("id_escuela")
                        .IsRequired()
                        .HasConstraintName("FK__director__id_esc__4316F928");

                    b.HasOne("GestionTrabajosDeGradoAPI.Models.usuario", "id_usuarioNavigation")
                        .WithMany("directors")
                        .HasForeignKey("id_usuario")
                        .IsRequired()
                        .HasConstraintName("FK__director__id_usu__440B1D61");

                    b.Navigation("id_escuelaNavigation");

                    b.Navigation("id_usuarioNavigation");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.escuela", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.facultad", "id_facultadNavigation")
                        .WithMany("escuelas")
                        .HasForeignKey("id_facultad")
                        .HasConstraintName("FK__escuela__id_facu__267ABA7A");

                    b.Navigation("id_facultadNavigation");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.estudiante", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.usuario", "id_usuarioNavigation")
                        .WithMany("estudiantes")
                        .HasForeignKey("id_usuario")
                        .HasConstraintName("FK__estudiant__id_us__3D5E1FD2");

                    b.Navigation("id_usuarioNavigation");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.evento", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.trabajos_de_grado", "id_trabajoNavigation")
                        .WithMany("eventos")
                        .HasForeignKey("id_trabajo")
                        .IsRequired()
                        .HasConstraintName("FK__eventos__id_trab__66603565");

                    b.HasOne("GestionTrabajosDeGradoAPI.Models.usuario", "id_usuarioNavigation")
                        .WithMany("eventos")
                        .HasForeignKey("id_usuario")
                        .IsRequired()
                        .HasConstraintName("FK__eventos__id_usua__6754599E");

                    b.Navigation("id_trabajoNavigation");

                    b.Navigation("id_usuarioNavigation");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.historial_de_cambio", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.usuario", "id_autorNavigation")
                        .WithMany("historial_de_cambios")
                        .HasForeignKey("id_autor")
                        .IsRequired()
                        .HasConstraintName("FK__historial__id_au__6D0D32F4");

                    b.HasOne("GestionTrabajosDeGradoAPI.Models.propuesta", "id_propuestaNavigation")
                        .WithMany("historial_de_cambios")
                        .HasForeignKey("id_propuesta")
                        .HasConstraintName("FK__historial__id_pr__6C190EBB");

                    b.HasOne("GestionTrabajosDeGradoAPI.Models.trabajos_de_grado", "id_trabajoNavigation")
                        .WithMany("historial_de_cambios")
                        .HasForeignKey("id_trabajo")
                        .HasConstraintName("FK__historial__id_tr__6B24EA82");

                    b.Navigation("id_autorNavigation");

                    b.Navigation("id_propuestaNavigation");

                    b.Navigation("id_trabajoNavigation");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.jurado", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.usuario", "id_usuarioNavigation")
                        .WithMany("jurados")
                        .HasForeignKey("id_usuario")
                        .IsRequired()
                        .HasConstraintName("FK__jurado__id_usuar__4AB81AF0");

                    b.Navigation("id_usuarioNavigation");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.linea_investigacion", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.escuela", "id_escuelaNavigation")
                        .WithMany("linea_investigacions")
                        .HasForeignKey("id_escuela")
                        .HasConstraintName("FK__linea_inv__id_es__5070F446");

                    b.Navigation("id_escuelaNavigation");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.propuesta", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.director", "id_directorNavigation")
                        .WithMany("propuesta")
                        .HasForeignKey("id_director")
                        .IsRequired()
                        .HasConstraintName("FK__propuesta__id_di__5441852A");

                    b.HasOne("GestionTrabajosDeGradoAPI.Models.linea_investigacion", "id_investigacionNavigation")
                        .WithMany("propuesta")
                        .HasForeignKey("id_investigacion")
                        .IsRequired()
                        .HasConstraintName("FK__propuesta__id_in__5535A963");

                    b.Navigation("id_directorNavigation");

                    b.Navigation("id_investigacionNavigation");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.trabajos_de_grado", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.propuesta", "id_propuestaNavigation")
                        .WithMany("trabajos_de_grados")
                        .HasForeignKey("id_propuesta")
                        .HasConstraintName("FK__trabajos___id_pr__5FB337D6");

                    b.Navigation("id_propuestaNavigation");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.usuario", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.escuela", "id_escuelaNavigation")
                        .WithMany("usuarios")
                        .HasForeignKey("id_escuela")
                        .HasConstraintName("FK__usuario__id_escu__2F10007B");

                    b.Navigation("id_escuelaNavigation");
                });

            modelBuilder.Entity("asesor_especializacion", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.asesor", null)
                        .WithMany()
                        .HasForeignKey("id_asesor")
                        .IsRequired()
                        .HasConstraintName("FK__asesor_es__id_as__38996AB5");

                    b.HasOne("GestionTrabajosDeGradoAPI.Models.especializacion", null)
                        .WithMany()
                        .HasForeignKey("id_especializacion")
                        .IsRequired()
                        .HasConstraintName("FK__asesor_es__id_es__398D8EEE");
                });

            modelBuilder.Entity("estudiante_propuestum", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.estudiante", null)
                        .WithMany()
                        .HasForeignKey("id_estudiante")
                        .IsRequired()
                        .HasConstraintName("FK__estudiant__id_es__59063A47");

                    b.HasOne("GestionTrabajosDeGradoAPI.Models.propuesta", null)
                        .WithMany()
                        .HasForeignKey("id_propuesta")
                        .IsRequired()
                        .HasConstraintName("FK__estudiant__id_pr__59FA5E80");
                });

            modelBuilder.Entity("estudiante_trabajo", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.estudiante", null)
                        .WithMany()
                        .HasForeignKey("id_estudiante")
                        .IsRequired()
                        .HasConstraintName("FK__estudiant__id_es__628FA481");

                    b.HasOne("GestionTrabajosDeGradoAPI.Models.trabajos_de_grado", null)
                        .WithMany()
                        .HasForeignKey("id_trabajo")
                        .IsRequired()
                        .HasConstraintName("FK__estudiant__id_tr__6383C8BA");
                });

            modelBuilder.Entity("jurados_trabajo", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.jurado", null)
                        .WithMany()
                        .HasForeignKey("id_jurado")
                        .IsRequired()
                        .HasConstraintName("FK__jurados_t__id_ju__73BA3083");

                    b.HasOne("GestionTrabajosDeGradoAPI.Models.trabajos_de_grado", null)
                        .WithMany()
                        .HasForeignKey("id_trabajo")
                        .IsRequired()
                        .HasConstraintName("FK__jurados_t__id_tr__74AE54BC");
                });

            modelBuilder.Entity("usuario_escuela", b =>
                {
                    b.HasOne("GestionTrabajosDeGradoAPI.Models.escuela", null)
                        .WithMany()
                        .HasForeignKey("id_escuela")
                        .IsRequired()
                        .HasConstraintName("FK__usuario_e__id_es__32E0915F");

                    b.HasOne("GestionTrabajosDeGradoAPI.Models.usuario", null)
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .IsRequired()
                        .HasConstraintName("FK__usuario_e__id_us__31EC6D26");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.asesor", b =>
                {
                    b.Navigation("asesor_trabajos");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.director", b =>
                {
                    b.Navigation("propuesta");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.escuela", b =>
                {
                    b.Navigation("directors");

                    b.Navigation("linea_investigacions");

                    b.Navigation("usuarios");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.facultad", b =>
                {
                    b.Navigation("escuelas");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.linea_investigacion", b =>
                {
                    b.Navigation("propuesta");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.propuesta", b =>
                {
                    b.Navigation("historial_de_cambios");

                    b.Navigation("trabajos_de_grados");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.trabajos_de_grado", b =>
                {
                    b.Navigation("asesor_trabajos");

                    b.Navigation("eventos");

                    b.Navigation("historial_de_cambios");
                });

            modelBuilder.Entity("GestionTrabajosDeGradoAPI.Models.usuario", b =>
                {
                    b.Navigation("asesors");

                    b.Navigation("directors");

                    b.Navigation("estudiantes");

                    b.Navigation("eventos");

                    b.Navigation("historial_de_cambios");

                    b.Navigation("jurados");
                });
#pragma warning restore 612, 618
        }
    }
}
